### ISSUE TITLE
Network may not restart or become enabled

### ISSUE THREAD

**Issue by spatterIight** [spatterIight/ansible-role-tinc#1]
The handler which is meant to restart and ensure the tinc networks are enabled and running  does not work in all scenarios:

```
---
- name: Restart Tinc
  ansible.builtin.service:
    name: tinc
    enabled: yes
    state: restarted
  tags: ansible-role-tinc
```

This handler only restarts/enables Tinc networks that are already 'registered' which the template unit service -- for lack of better terminology.

Meaning, restarting the tinc service will only restart tinc services that have already been enabled via something like:
`systemctl enable --now tinc@mynetwork`
